-- Generated by tinty — do not edit manually (scheme: base16-da-one-sea)
return {
  foreground    = "#ffffff",
  background    = "#22273d",
  cursor_bg     = "#ffffff",
  cursor_border = "#ffffff",
  cursor_fg     = "#22273d",
  selection_bg  = "#525866",
  selection_fg  = "#ffffff",
  ansi = {
    "#22273d", "#fa7883", "#98c379", "#ff9470",
    "#6bb8ff", "#e799ff", "#8af5ff", "#ffffff",
  },
  brights = {
    "#878d96", "#fa7883", "#98c379", "#ff9470",
    "#6bb8ff", "#e799ff", "#8af5ff", "#ffffff",
  },
}
