-- Generated by tinty — do not edit manually (scheme: base24-gogh-astrodark)
return {
  foreground    = "#9b9fa9",
  background    = "#1a1d23",
  cursor_bg     = "#9b9fa9",
  cursor_border = "#9b9fa9",
  cursor_fg     = "#1a1d23",
  selection_bg  = "#576176",
  selection_fg  = "#9b9fa9",
  ansi = {
    "#1a1d23", "#f8747e", "#75ad47", "#d09214",
    "#50a4e9", "#cc83e3", "#00b298", "#9b9fa9",
  },
  brights = {
    "#576176", "#faa5ab", "#a5cd84", "#efbd58",
    "#8dc3f1", "#deaeed", "#27ffdf", "#caccd3",
  },
}
