-- Generated by tinty — do not edit manually (scheme: base16-solarized-dark)
return {
  foreground    = "#93a1a1",
  background    = "#002b36",
  cursor_bg     = "#93a1a1",
  cursor_border = "#93a1a1",
  cursor_fg     = "#002b36",
  selection_bg  = "#586e75",
  selection_fg  = "#93a1a1",
  ansi = {
    "#002b36", "#dc322f", "#859900", "#b58900",
    "#268bd2", "#6c71c4", "#2aa198", "#93a1a1",
  },
  brights = {
    "#657b83", "#dc322f", "#859900", "#b58900",
    "#268bd2", "#6c71c4", "#2aa198", "#fdf6e3",
  },
}
