#!/usr/bin/env bash
# Generates ~/.config/wezterm/colors.lua (and writes it to the chezmoi source)
# from the active tinty base16/base24 scheme. Run as a tinty hook after tinted-shell.

ARTIFACTS="$HOME/.local/share/tinted-theming/tinty/artifacts"
SCHEMES_DIR="$HOME/.local/share/tinted-theming/tinty/repos/schemes"

SCHEME=$(cat "$ARTIFACTS/current_scheme" 2>/dev/null)
[[ -z "$SCHEME" ]] && exit 0

SYSTEM="${SCHEME%%-*}"
NAME="${SCHEME#*-}"
YAML="$SCHEMES_DIR/$SYSTEM/$NAME.yaml"
[[ -f "$YAML" ]] || exit 0

declare -A C
while IFS= read -r line; do
    if [[ "$line" =~ ^[[:space:]]*(base[0-9A-Fa-f]{2}):[[:space:]]*\"#([0-9A-Fa-f]{6})\" ]]; then
        C["${BASH_REMATCH[1],,}"]="#${BASH_REMATCH[2],,}"
    fi
done < "$YAML"

[[ -z "${C[base00]}" || -z "${C[base05]}" ]] && exit 0

lua_content="-- Generated by tinty — do not edit manually (scheme: $SCHEME)
return {
  foreground    = \"${C[base05]}\",
  background    = \"${C[base00]}\",
  cursor_bg     = \"${C[base05]}\",
  cursor_border = \"${C[base05]}\",
  cursor_fg     = \"${C[base00]}\",
  selection_bg  = \"${C[base02]}\",
  selection_fg  = \"${C[base05]}\",
  ansi = {
    \"${C[base00]}\", \"${C[base08]}\", \"${C[base0b]}\", \"${C[base0a]}\",
    \"${C[base0d]}\", \"${C[base0e]}\", \"${C[base0c]}\", \"${C[base05]}\",
  },
  brights = {
    \"${C[base03]}\", \"${C[base08]}\", \"${C[base0b]}\", \"${C[base0a]}\",
    \"${C[base0d]}\", \"${C[base0e]}\", \"${C[base0c]}\", \"${C[base07]}\",
  },
}"

# Write to chezmoi source so the file is tracked in git
CHEZMOI_SRC="$(chezmoi source-path 2>/dev/null)"
if [[ -n "$CHEZMOI_SRC" ]]; then
    echo "$lua_content" > "$CHEZMOI_SRC/dot_config/wezterm/colors.lua"
fi

# Also write to the deployed location for immediate effect on Linux
mkdir -p "$HOME/.config/wezterm"
echo "$lua_content" > "$HOME/.config/wezterm/colors.lua"
