#!/usr/bin/env bash
# Generates ~/.config/wezterm/colors.lua from the active tinty base16/base24 scheme.
# Run as a tinty hook after tinted-shell. The generated file is NOT tracked by git;
# instead this script records the picked scheme in the chezmoi source's single
# tracked source of truth (.chezmoidata/theme.toml) so other machines regenerate it.

ARTIFACTS="$HOME/.local/share/tinted-theming/tinty/artifacts"
SCHEMES_DIR="$HOME/.local/share/tinted-theming/tinty/repos/schemes"
CUSTOM_DIR="$HOME/.local/share/tinted-theming/tinty/custom-schemes"

# Scheme comes from $1 (so chezmoi apply can pass the default-scheme directly),
# falling back to the last `theme` pick recorded by tinty.
SCHEME="${1:-$(cat "$ARTIFACTS/current_scheme" 2>/dev/null)}"
[[ -z "$SCHEME" ]] && exit 0

SYSTEM="${SCHEME%%-*}"
NAME="${SCHEME#*-}"
# Prefer the official catalog clone; fall back to our chezmoi-shipped custom
# schemes (e.g. base16-feb) which tinty does not place under repos/.
YAML="$SCHEMES_DIR/$SYSTEM/$NAME.yaml"
[[ -f "$YAML" ]] || YAML="$CUSTOM_DIR/$SYSTEM/$NAME.yaml"
[[ -f "$YAML" ]] || exit 0

# Extract one palette entry by base key, lowercased. Deliberately avoids bash-4
# features (associative arrays, ${var,,}) — macOS ships bash 3.2, where
# `declare -A` fails and every color collapses to one value (the all-#xxxxxx
# corruption this used to emit). grep -i makes the key match casing-agnostic
# (yaml uses base0A..base0F uppercase); sed/tr keep it portable across BSD+GNU.
color() {
    grep -iE "^[[:space:]]*$1:[[:space:]]*\"#[0-9A-Fa-f]{6}\"" "$YAML" \
        | head -n1 \
        | sed -E 's/.*"(#[0-9A-Fa-f]{6})".*/\1/' \
        | tr 'A-F' 'a-f'
}

base00=$(color base00); base02=$(color base02); base03=$(color base03)
base05=$(color base05); base07=$(color base07); base08=$(color base08)
base0a=$(color base0A); base0b=$(color base0B); base0c=$(color base0C)
base0d=$(color base0D); base0e=$(color base0E)

# base24 schemes carry distinct bright ANSI colors in base12-17; base16 schemes
# don't, so fall back to the normal accents there (identical output for base16).
base12=$(color base12); base13=$(color base13); base14=$(color base14)
base15=$(color base15); base16=$(color base16); base17=$(color base17)
br_red="${base12:-$base08}"; br_grn="${base14:-$base0b}"; br_yel="${base13:-$base0a}"
br_blu="${base16:-$base0d}"; br_mag="${base17:-$base0e}"; br_cyn="${base15:-$base0c}"

# Bail if the scheme didn't parse (missing essentials) so we never overwrite a
# good colors.lua with a half-empty one.
[[ -z "$base00" || -z "$base05" ]] && exit 0

# Optional background-override from config.toml overrides the scheme's base00, so
# every background-derived field (bg, cursor_fg, ansi black) tracks the fixed hex.
bg_override=$(grep -iE '^[[:space:]]*background-override[[:space:]]*=[[:space:]]*"#[0-9A-Fa-f]{6}"' \
    "$HOME/.config/tinted-theming/tinty/config.toml" 2>/dev/null \
    | head -n1 | sed -E 's/.*"(#[0-9A-Fa-f]{6})".*/\1/' | tr 'A-F' 'a-f')
[[ -n "$bg_override" ]] && base00="$bg_override"

# GlazeWM's focused-window outline tracks the theme's green (base0B), the same way
# colors.lua tracks the palette: rewrite the single border line tagged `tinty:base0B`
# in a deployed glazewm config.yaml, leaving every other line (incl. other_windows'
# border) untouched. -i.bak is the portable in-place form across GNU and BSD sed
# (macOS bash 3.2). No-op when the file is absent (plain Linux, no GlazeWM).
set_glazewm_border() {
    local file="$1"
    [[ -n "$base0b" && -f "$file" ]] || return 0
    sed -i.bak -E \
        "s|^([[:space:]]*color:[[:space:]]*')#[0-9A-Fa-f]{6}('[[:space:]]*#[[:space:]]*tinty:base0B.*)\$|\\1${base0b}\\2|" \
        "$file" 2>/dev/null && rm -f "$file.bak"
}

# Hot-reload GlazeWM so the new outline shows without a manual reload — `command`
# is a no-op when GlazeWM isn't running (a fresh launch reads the file anyway).
# Windows CLI from WSL takes priority; the native binary covers macOS.
reload_glazewm() {
    if command -v glazewm.exe >/dev/null 2>&1; then
        glazewm.exe command wm-reload-config >/dev/null 2>&1 || true
    elif command -v glazewm >/dev/null 2>&1; then
        glazewm command wm-reload-config >/dev/null 2>&1 || true
    fi
}

lua_content="-- Generated by tinty — do not edit manually (scheme: $SCHEME)
return {
  foreground    = \"$base05\",
  background    = \"$base00\",
  cursor_bg     = \"$base05\",
  cursor_border = \"$base05\",
  cursor_fg     = \"$base00\",
  selection_bg  = \"$base02\",
  selection_fg  = \"$base05\",
  ansi = {
    \"$base00\", \"$base08\", \"$base0b\", \"$base0a\",
    \"$base0d\", \"$base0e\", \"$base0c\", \"$base05\",
  },
  brights = {
    \"$base03\", \"$br_red\", \"$br_grn\", \"$br_yel\",
    \"$br_blu\", \"$br_mag\", \"$br_cyn\", \"$base07\",
  },
}"

# tinty runs this hook on every `tinty init` (each shell start), not only on a
# `theme` switch. On a plain start the scheme is unchanged, so the generated lua
# already matches what's deployed — bail before the expensive `chezmoi source-path`
# spawn (~120ms) and the file writes. Only a real theme change (differing content)
# falls through to regenerate. This is the single biggest shell-startup cost.
DEPLOY="$HOME/.config/wezterm/colors.lua"
[[ -f "$DEPLOY" && "$lua_content" == "$(cat "$DEPLOY")" ]] && exit 0

# Sync the active scheme to the chezmoi source as the SINGLE tracked source of
# truth: .chezmoidata/theme.toml. The generated artifacts (colors.lua, theme.css)
# are no longer tracked — other machines run `tinty apply <scheme>` from this on
# `chezmoi apply` (run_after_generate-shell-init.sh.tmpl) and regenerate them
# locally, so they can never conflict. We rewrite only the one `scheme` value line in
# place (portable sed -i.bak) to preserve the file's comment header; the border green
# GlazeWM needs is derived from this scheme by config.yaml.tmpl (scheme-base0b.sh), so
# there's no second value to write here. We reach here only on a real theme change (the
# unchanged-content guard above already exited), so theme.toml — and the one-line commit
# `just push` makes from it — changes only when you switch.
CHEZMOI_SRC="$(chezmoi source-path 2>/dev/null)"
theme_data="$CHEZMOI_SRC/.chezmoidata/theme.toml"
if [[ -n "$CHEZMOI_SRC" && -f "$theme_data" ]]; then
    sed -i.bak -E \
        -e "s|^([[:space:]]*scheme[[:space:]]*=[[:space:]]*).*|\\1\"${SCHEME}\"|" \
        "$theme_data" 2>/dev/null && rm -f "$theme_data.bak"
fi

# Also write to the deployed location for immediate effect on Linux
mkdir -p "$HOME/.config/wezterm"
echo "$lua_content" > "$HOME/.config/wezterm/colors.lua"
# macOS runs GlazeWM off ~/.glzr directly (no Windows mirror); WSL handles its
# Windows copy below. Harmless no-op on plain Linux.
set_glazewm_border "$HOME/.glzr/glazewm/config.yaml"

# WSL: the running terminal is the native wezterm.exe, which reads its config from
# the Windows profile, not this Linux $HOME. Mirror colors.lua there too so its
# config-reload watch (wezterm.lua) re-reads it and refreshes bg/cursor/overlay live
# as the `theme` switcher previews each scheme. The Windows-dir derivation matches
# run_after_mirror-config-to-windows.sh and is CACHED — cmd.exe is ~100ms and the
# picker rewrites this file on every focus, so we resolve it once. Strict guards
# (drive letter + absolute wslpath result) keep a failed cmd.exe from writing under
# the wrong dir.
if grep -qi microsoft /proc/version 2>/dev/null; then
    cache="$HOME/.cache/tinty-wezterm-win-dir"
    if [[ -s "$cache" ]]; then
        win_dir="$(cat "$cache")"
    else
        win_dir=""
        up="$(cmd.exe /c 'echo %USERPROFILE%' 2>/dev/null | tr -d '\r\n')"
        case "$up" in
            [A-Za-z]:*)
                winhome="$(wslpath -u "$up" 2>/dev/null)" || winhome=""
                case "$winhome" in
                    /*) [[ -d "$winhome" ]] && win_dir="$winhome/.config/wezterm" ;;
                esac
                ;;
        esac
        if [[ -n "$win_dir" ]]; then
            mkdir -p "$(dirname "$cache")"
            printf '%s\n' "$win_dir" > "$cache"
        fi
    fi
    if [[ -n "$win_dir" ]]; then
        mkdir -p "$win_dir"
        echo "$lua_content" > "$win_dir/colors.lua"
        # GlazeWM reads %USERPROFILE%\.glzr; win_dir is "$winhome/.config/wezterm",
        # so strip that suffix to reach the live config the running WM actually uses.
        set_glazewm_border "${win_dir%/.config/wezterm}/.glzr/glazewm/config.yaml"
    fi
fi

# Hot-reload GlazeWM so the outline retints immediately on a `theme` switch (we only
# reach here when the scheme actually changed — the unchanged-content guard above
# exits first).
reload_glazewm
