#!/usr/bin/env bash
# Generates the Zebar bar's theme.css from the active tinty base16/base24 scheme,
# so the GlazeWM top bar tracks the same palette as the terminal. Run as a tinty
# hook after tinted-shell, alongside wezterm-colors.sh.
#
# Writes CSS custom properties (--bg, --fg, --accent, …) that custom-topbar's
# index.html consumes. Triple-write, same as wezterm-colors.sh: chezmoi source
# (tracked), the deployed ~/.glzr copy, and — on WSL — the Windows profile where
# the native Zebar.exe actually reads it.

ARTIFACTS="$HOME/.local/share/tinted-theming/tinty/artifacts"
SCHEMES_DIR="$HOME/.local/share/tinted-theming/tinty/repos/schemes"
CUSTOM_DIR="$HOME/.local/share/tinted-theming/tinty/custom-schemes"

# Scheme from $1 (chezmoi apply passes the default-scheme), else the last pick.
SCHEME="${1:-$(cat "$ARTIFACTS/current_scheme" 2>/dev/null)}"
[[ -z "$SCHEME" ]] && exit 0

SYSTEM="${SCHEME%%-*}"
NAME="${SCHEME#*-}"
YAML="$SCHEMES_DIR/$SYSTEM/$NAME.yaml"
[[ -f "$YAML" ]] || YAML="$CUSTOM_DIR/$SYSTEM/$NAME.yaml"
[[ -f "$YAML" ]] || exit 0

# Extract one palette entry by base key (portable: macOS bash 3.2, BSD+GNU sed).
color() {
    grep -iE "^[[:space:]]*$1:[[:space:]]*\"#[0-9A-Fa-f]{6}\"" "$YAML" \
        | head -n1 \
        | sed -E 's/.*"(#[0-9A-Fa-f]{6})".*/\1/' \
        | tr 'A-F' 'a-f'
}

base00=$(color base00)  # background
base01=$(color base01)  # lighter background
base03=$(color base03)  # comments / muted
base05=$(color base05)  # foreground
base0b=$(color base0B)  # green
base0d=$(color base0D)  # blue / accent

# Bail if the scheme didn't parse, so we never overwrite a good theme.css.
[[ -z "$base00" || -z "$base05" ]] && exit 0

css_content="/* Generated by tinty — do not edit manually (scheme: $SCHEME) */
:root {
  --bg: $base00;
  --bg-alt: $base01;
  --muted: $base03;
  --fg: $base05;
  --green: $base0b;
  --accent: $base0d;
}"

REL="dot_glzr/zebar/custom-topbar/theme.css"
LIVE="$HOME/.glzr/zebar/custom-topbar/theme.css"

# Tracked chezmoi source.
CHEZMOI_SRC="$(chezmoi source-path 2>/dev/null)"
[[ -n "$CHEZMOI_SRC" ]] && printf '%s\n' "$css_content" > "$CHEZMOI_SRC/$REL"

# Deployed copy (Linux / macOS read this directly).
mkdir -p "$(dirname "$LIVE")"
printf '%s\n' "$css_content" > "$LIVE"

# WSL: the native Zebar.exe reads from the Windows profile, not this $HOME.
# Mirror there too, reusing the cached win-dir derivation pattern.
if grep -qi microsoft /proc/version 2>/dev/null; then
    cache="$HOME/.cache/tinty-zebar-win-dir"
    if [[ -s "$cache" ]]; then
        win_dir="$(cat "$cache")"
    else
        win_dir=""
        up="$(cmd.exe /c 'echo %USERPROFILE%' 2>/dev/null | tr -d '\r\n')"
        case "$up" in
            [A-Za-z]:*)
                winhome="$(wslpath -u "$up" 2>/dev/null)" || winhome=""
                case "$winhome" in
                    /*) [[ -d "$winhome" ]] && win_dir="$winhome/.glzr/zebar/custom-topbar" ;;
                esac
                ;;
        esac
        if [[ -n "$win_dir" ]]; then
            mkdir -p "$(dirname "$cache")"
            printf '%s\n' "$win_dir" > "$cache"
        fi
    fi
    if [[ -n "$win_dir" ]]; then
        mkdir -p "$win_dir"
        printf '%s\n' "$css_content" > "$win_dir/theme.css"
    fi
fi
