#!/usr/bin/env bash
# Generates the Zebar bar's theme.css from the active tinty base16/base24 scheme,
# so the GlazeWM top bar tracks the same palette as the terminal. Run as a tinty
# hook after tinted-shell, alongside wezterm-colors.sh.
#
# Writes CSS custom properties (--bg, --fg, --accent, …) that custom-topbar's
# index.html consumes. Triple-write, same as wezterm-colors.sh: chezmoi source
# (tracked), the deployed ~/.glzr copy, and — on WSL — the Windows profile where
# the native Zebar.exe actually reads it.

ARTIFACTS="$HOME/.local/share/tinted-theming/tinty/artifacts"
SCHEMES_DIR="$HOME/.local/share/tinted-theming/tinty/repos/schemes"
CUSTOM_DIR="$HOME/.local/share/tinted-theming/tinty/custom-schemes"

# Scheme from $1 (chezmoi apply passes the default-scheme), else the last pick.
SCHEME="${1:-$(cat "$ARTIFACTS/current_scheme" 2>/dev/null)}"
[[ -z "$SCHEME" ]] && exit 0

SYSTEM="${SCHEME%%-*}"
NAME="${SCHEME#*-}"
YAML="$SCHEMES_DIR/$SYSTEM/$NAME.yaml"
[[ -f "$YAML" ]] || YAML="$CUSTOM_DIR/$SYSTEM/$NAME.yaml"
[[ -f "$YAML" ]] || exit 0

# Extract one palette entry by base key (portable: macOS bash 3.2, BSD+GNU sed).
color() {
    grep -iE "^[[:space:]]*$1:[[:space:]]*\"#[0-9A-Fa-f]{6}\"" "$YAML" \
        | head -n1 \
        | sed -E 's/.*"(#[0-9A-Fa-f]{6})".*/\1/' \
        | tr 'A-F' 'a-f'
}

base00=$(color base00)  # background
base01=$(color base01)  # lighter background
base03=$(color base03)  # comments / muted
base05=$(color base05)  # foreground
base0b=$(color base0B)  # green
base0d=$(color base0D)  # blue / accent

# Bail if the scheme didn't parse, so we never overwrite a good theme.css.
[[ -z "$base00" || -z "$base05" ]] && exit 0

# Optional background-override from config.toml overrides the scheme's base00 (--bg).
bg_override=$(grep -iE '^[[:space:]]*background-override[[:space:]]*=[[:space:]]*"#[0-9A-Fa-f]{6}"' \
    "$HOME/.config/tinted-theming/tinty/config.toml" 2>/dev/null \
    | head -n1 | sed -E 's/.*"(#[0-9A-Fa-f]{6})".*/\1/' | tr 'A-F' 'a-f')
[[ -n "$bg_override" ]] && base00="$bg_override"

css_content="/* Generated by tinty — do not edit manually (scheme: $SCHEME) */
:root {
  --bg: $base00;
  --bg-alt: $base01;
  --muted: $base03;
  --fg: $base05;
  --green: $base0b;
  --accent: $base0d;
}"

REL="dot_glzr/zebar/custom-topbar/theme.css"
LIVE="$HOME/.glzr/zebar/custom-topbar/theme.css"

# tinty runs this hook on every `tinty init` (each shell start), not only on a
# `theme` switch. On a plain start the scheme is unchanged, so the generated CSS
# already matches what's deployed — bail before the expensive `chezmoi source-path`
# spawn (~120ms), the file writes, AND the Zebar restart. Crucially this stops every
# new terminal from kill+relaunching Zebar across the WSL->Windows boundary (a
# cmd.exe stall that hangs the shell before its prompt, keys echoing raw into the
# void). Only a real theme change (differing CSS) falls through to regenerate.
[[ -f "$LIVE" && "$css_content" == "$(cat "$LIVE")" ]] && exit 0

# Tracked chezmoi source.
CHEZMOI_SRC="$(chezmoi source-path 2>/dev/null)"
[[ -n "$CHEZMOI_SRC" ]] && printf '%s\n' "$css_content" > "$CHEZMOI_SRC/$REL"

# Deployed copy (Linux / macOS read this directly).
mkdir -p "$(dirname "$LIVE")"
printf '%s\n' "$css_content" > "$LIVE"

# WSL: the native Zebar.exe reads from the Windows profile, not this $HOME.
# Mirror there too, reusing the cached win-dir derivation pattern.
if grep -qi microsoft /proc/version 2>/dev/null; then
    cache="$HOME/.cache/tinty-zebar-win-dir"
    if [[ -s "$cache" ]]; then
        win_dir="$(cat "$cache")"
    else
        win_dir=""
        up="$(cmd.exe /c 'echo %USERPROFILE%' 2>/dev/null | tr -d '\r\n')"
        case "$up" in
            [A-Za-z]:*)
                winhome="$(wslpath -u "$up" 2>/dev/null)" || winhome=""
                case "$winhome" in
                    /*) [[ -d "$winhome" ]] && win_dir="$winhome/.glzr/zebar/custom-topbar" ;;
                esac
                ;;
        esac
        if [[ -n "$win_dir" ]]; then
            mkdir -p "$(dirname "$cache")"
            printf '%s\n' "$win_dir" > "$cache"
        fi
    fi
    if [[ -n "$win_dir" ]]; then
        mkdir -p "$win_dir"
        printf '%s\n' "$css_content" > "$win_dir/theme.css"
    fi
fi

# ── Restart Zebar so the new palette actually shows ──────────────────────────
# Zebar has no reload IPC (only start-widget/startup), so it reads theme.css once
# at launch — a live `theme` switch rewrites the CSS above but leaves the running
# bar painted with the OLD colors. Restart it here, the one place that knows the
# palette just changed (the unchanged case already exited above, so reaching here
# means a real `theme` switch), but ONLY if a bar is already up, so we never spawn
# one the user deliberately closed. Best-effort and non-fatal: a failed retint must
# never break `theme`. (chezmoi apply uses a separate hook —
# run_onchange_after_restart-glazewm-zebar.sh — for structural config changes.)
if grep -qi microsoft /proc/version 2>/dev/null; then
    # WSL → native Zebar.exe on the Windows host. taskkill's exit code is our
    # "was it running" signal (pgrep can't see Windows processes from WSL). The
    # relaunch is fully detached — `( … & )` with stdin from /dev/null — so the
    # GUI's inherited handles can't keep WSL interop (and the shell) blocked.
    if command -v taskkill.exe >/dev/null 2>&1 && taskkill.exe /IM zebar.exe /F >/dev/null 2>&1; then
        ( cmd.exe /c start "" zebar.exe </dev/null >/dev/null 2>&1 & ) || true
    fi
elif pgrep -x zebar >/dev/null 2>&1; then
    pkill -x zebar 2>/dev/null || true
    # Let the old process release its windows before the new one binds.
    for _ in 1 2 3 4 5 6 7 8 9 10; do pgrep -x zebar >/dev/null 2>&1 || break; sleep 0.2; done
    if [[ -d /Applications/Zebar.app ]]; then
        open -na /Applications/Zebar.app >/dev/null 2>&1 || true   # macOS
    else
        nohup zebar startup >/dev/null 2>&1 &                      # Linux
    fi
fi
