#!/usr/bin/env bash
# Generates ~/.config/tmux/colors.conf from the active tinty base16/base24
# scheme, sources it into a running tmux server, and pushes the palette out to
# every attached terminal as OSC. Runs as the tinty hook after tinted-shell
# (see config.toml beside this file). Two channels because tmux's own
# surfaces are not ANSI slots (base02, the active window label's background,
# has none) and the tty push is what a second attached client needs — see
# CLAUDE.md's "tinty owns the palette" and manual → internals/tmux, Palette
# delivery.
#
# The conf is written whether or not tmux is running; the source-file and the
# OSC only happen when there is a server to talk to.

DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/tinted-theming/tinty"
SCHEMES_DIR="$DATA_DIR/repos/schemes"
CUSTOM_DIR="$DATA_DIR/custom-schemes"

# Scheme comes from $1, falling back to the last pick tinty recorded. tinty
# versions differ on where they write current_scheme (the data root or its
# artifacts/ subdir); read whichever exists. Carried over verbatim from
# wezterm-colors.sh — it was right, and the reason is still true.
SCHEME="${1:-}"
[[ -z "$SCHEME" ]] && SCHEME="$(cat "$DATA_DIR/current_scheme" 2>/dev/null)"
[[ -z "$SCHEME" ]] && SCHEME="$(cat "$DATA_DIR/artifacts/current_scheme" 2>/dev/null)"
[[ -z "$SCHEME" ]] && exit 0

SYSTEM="${SCHEME%%-*}"
NAME="${SCHEME#*-}"
YAML="$SCHEMES_DIR/$SYSTEM/$NAME.yaml"
[[ -f "$YAML" ]] || YAML="$CUSTOM_DIR/$SYSTEM/$NAME.yaml"
[[ -f "$YAML" ]] || exit 0

# One palette entry by base key, lowercased. Deliberately avoids bash-4
# features (associative arrays, ${var,,}) — macOS ships bash 3.2, where
# `declare -A` fails and every colour collapses to one value, the
# all-#xxxxxx corruption an earlier generator once emitted.
color() {
    grep -iE "^[[:space:]]*$1:[[:space:]]*\"#[0-9A-Fa-f]{6}\"" "$YAML" \
        | head -n1 \
        | sed -E 's/.*"(#[0-9A-Fa-f]{6})".*/\1/' \
        | tr 'A-F' 'a-f'
}

base00=$(color base00); base01=$(color base01); base02=$(color base02)
base03=$(color base03); base04=$(color base04); base05=$(color base05)
base07=$(color base07); base08=$(color base08); base09=$(color base09)
base0a=$(color base0A); base0b=$(color base0B); base0c=$(color base0C)
base0d=$(color base0D); base0e=$(color base0E); base0f=$(color base0F)

# No base24 brights: the "bright" ANSI slots (8-15) reuse the base16 colours.
br_red="$base08"; br_grn="$base0b"; br_yel="$base0a"
br_blu="$base0d"; br_mag="$base0e"; br_cyn="$base0c"

# A scheme that did not parse must never overwrite a good conf with a
# half-empty one.
[[ -z "$base00" || -z "$base05" || -z "$base02" || -z "$base03" ]] && exit 0

# ── the conf ────────────────────────────────────────────────────────────────
#
# Only STYLES are written here, never formats. tmux.conf owns the bar's shape
# (which segment goes where, what the label says); this file owns nothing but
# its colours, so a scheme change can never move a segment. The style names
# are exactly the ones tmux.conf sets with ANSI slots, so sourcing this is a
# pure override.
conf_content="# Generated by tinty — do not edit manually (scheme: $SCHEME)
# Written by ~/.config/tinted-theming/tinty/tmux-colors.sh. Sourced from
# tmux.conf at start and source-file'd live on every apply.
set -g status-style 'bg=$base00,fg=$base03'
set -g message-style 'bg=$base02,fg=$base05'
set -g message-command-style 'bg=$base02,fg=$base05'
setw -g window-status-style 'bg=$base00,fg=$base03'
setw -g window-status-current-style 'bg=$base02,fg=$base05,bold'
setw -g window-status-activity-style 'bg=$base00,fg=$base0a'
setw -g mode-style 'bg=$base02,fg=$base05'
setw -g pane-border-style 'fg=$base02'
setw -g pane-active-border-style 'fg=$base04'"

DEPLOY="${XDG_CONFIG_HOME:-$HOME/.config}/tmux/colors.conf"

# ── the OSC push ────────────────────────────────────────────────────────────
#
# The write is guarded on content (tinty runs this on every shell start, not
# only on a switch) but the OSC push is not: a client that attached since
# the last write still has the old palette on its wire.
#
# TRAP: `$TMUX` names the CALLING shell's server (`<socket>,<pid>,<session>`)
# — needed so this reaches the server you're actually looking at on a machine
# running more than one (a `-L` gate, a nested ssh session), not whichever
# owns the default socket.
tmux_at() {
    if [ -n "${TMUX:-}" ]; then
        tmux -S "${TMUX%%,*}" "$@"
    else
        tmux "$@"
    fi
}

osc_push() {
    command -v tmux > /dev/null 2>&1 || return 0
    tmux_at list-clients -F '#{client_tty}' > /dev/null 2>&1 || return 0

    # TRAP: ESC held as a character ($'\033'), never fed through `printf %b`
    # — measured 2026-09-01, `%b` doubled a backslash and corrupted every
    # slot after the first. `%s` below, for the same reason.
    local ESC=$'\033' ST=$'\033\\'
    local seq="" i=0 c
    # OSC 4 — the sixteen ANSI slots tmux reads colour0-15 out of: base00 08
    # 0B 0A 0D 0E 0C 05, then base03 and the brights.
    for c in "$base00" "$base08" "$base0b" "$base0a" "$base0d" "$base0e" "$base0c" "$base05" \
             "$base03" "$br_red" "$br_grn" "$br_yel" "$br_blu" "$br_mag" "$br_cyn" "$base07"; do
        seq="$seq$ESC]4;$i;$c$ST"
        i=$((i + 1))
    done
    # 10 foreground, 11 background, 12 cursor — the three the ANSI slots do
    # not carry. 11 is the one F6 is judged by from across the room.
    seq="$seq$ESC]10;$base05$ST$ESC]11;$base00$ST$ESC]12;$base05$ST"

    local tty
    while IFS= read -r tty; do
        [[ -w "$tty" ]] || continue
        printf '%s' "$seq" > "$tty" 2>/dev/null || true
    done < <(tmux_at list-clients -F '#{client_tty}' 2>/dev/null | sort -u)
}

if [[ -f "$DEPLOY" && "$conf_content" == "$(cat "$DEPLOY")" ]]; then
    # Unchanged scheme — but a client attached since the last apply still has
    # the previous palette on its wire, so the OSC still goes out.
    osc_push
    exit 0
fi

mkdir -p "$(dirname "$DEPLOY")"
printf '%s\n' "$conf_content" > "$DEPLOY"

# Live-apply into a running server. `source-file` on a server that is not
# there is an error, not a failure of this hook.
if command -v tmux > /dev/null 2>&1 && tmux_at has-session > /dev/null 2>&1; then
    tmux_at source-file "$DEPLOY" > /dev/null 2>&1 || true
fi
osc_push
