#!/usr/bin/env bash
# Generates ~/.config/wezterm/colors.lua (and writes it to the chezmoi source)
# from the active tinty base16/base24 scheme. Run as a tinty hook after tinted-shell.

ARTIFACTS="$HOME/.local/share/tinted-theming/tinty/artifacts"
SCHEMES_DIR="$HOME/.local/share/tinted-theming/tinty/repos/schemes"
CUSTOM_DIR="$HOME/.local/share/tinted-theming/tinty/custom-schemes"

# Scheme comes from $1 (so chezmoi apply can pass the default-scheme directly),
# falling back to the last `theme` pick recorded by tinty.
SCHEME="${1:-$(cat "$ARTIFACTS/current_scheme" 2>/dev/null)}"
[[ -z "$SCHEME" ]] && exit 0

SYSTEM="${SCHEME%%-*}"
NAME="${SCHEME#*-}"
# Prefer the official catalog clone; fall back to our chezmoi-shipped custom
# schemes (e.g. base16-feb) which tinty does not place under repos/.
YAML="$SCHEMES_DIR/$SYSTEM/$NAME.yaml"
[[ -f "$YAML" ]] || YAML="$CUSTOM_DIR/$SYSTEM/$NAME.yaml"
[[ -f "$YAML" ]] || exit 0

# Extract one palette entry by base key, lowercased. Deliberately avoids bash-4
# features (associative arrays, ${var,,}) — macOS ships bash 3.2, where
# `declare -A` fails and every color collapses to one value (the all-#xxxxxx
# corruption this used to emit). grep -i makes the key match casing-agnostic
# (yaml uses base0A..base0F uppercase); sed/tr keep it portable across BSD+GNU.
color() {
    grep -iE "^[[:space:]]*$1:[[:space:]]*\"#[0-9A-Fa-f]{6}\"" "$YAML" \
        | head -n1 \
        | sed -E 's/.*"(#[0-9A-Fa-f]{6})".*/\1/' \
        | tr 'A-F' 'a-f'
}

base00=$(color base00); base02=$(color base02); base03=$(color base03)
base05=$(color base05); base07=$(color base07); base08=$(color base08)
base0a=$(color base0A); base0b=$(color base0B); base0c=$(color base0C)
base0d=$(color base0D); base0e=$(color base0E)

# Bail if the scheme didn't parse (missing essentials) so we never overwrite a
# good colors.lua with a half-empty one.
[[ -z "$base00" || -z "$base05" ]] && exit 0

lua_content="-- Generated by tinty — do not edit manually (scheme: $SCHEME)
return {
  foreground    = \"$base05\",
  background    = \"$base00\",
  cursor_bg     = \"$base05\",
  cursor_border = \"$base05\",
  cursor_fg     = \"$base00\",
  selection_bg  = \"$base02\",
  selection_fg  = \"$base05\",
  ansi = {
    \"$base00\", \"$base08\", \"$base0b\", \"$base0a\",
    \"$base0d\", \"$base0e\", \"$base0c\", \"$base05\",
  },
  brights = {
    \"$base03\", \"$base08\", \"$base0b\", \"$base0a\",
    \"$base0d\", \"$base0e\", \"$base0c\", \"$base07\",
  },
}"

# Write to chezmoi source so the file is tracked in git
CHEZMOI_SRC="$(chezmoi source-path 2>/dev/null)"
if [[ -n "$CHEZMOI_SRC" ]]; then
    echo "$lua_content" > "$CHEZMOI_SRC/dot_config/wezterm/colors.lua"
fi

# Also write to the deployed location for immediate effect on Linux
mkdir -p "$HOME/.config/wezterm"
echo "$lua_content" > "$HOME/.config/wezterm/colors.lua"
