FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=xterm-256color
ENV LANG=C.UTF-8

RUN apt-get update && apt-get install -y \
  git \
  zsh \
  git \
  curl \
  wget \
  unzip \
  ca-certificates \
  ripgrep \
  fd-find \
  fzf \
  tmux \
  neovim \
  rsync \
  build-essential \
  python3 \
  python3-pip \
  && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/zsh dev

USER dev
WORKDIR /home/dev

# Install Oh My Zsh
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Clone Neovim dotfiles
RUN git clone https://github.com/yesitsfebreeze/nvim /tmp/dontmindme
RUN rsync -a /tmp/dontmindme/ .
RUN rm -rf /tmp/dontmindme

# Download .shrc from .files dotfiles
RUN curl -fsSL https://raw.githubusercontent.com/yesitsfebreeze/.files/main/.shrc -o ~/.shrc

# Create basic .zshrc with color support
RUN echo 'export ZSH="$HOME/.oh-my-zsh"' > ~/.zshrc && \
    echo 'ZSH_THEME="amuse"' >> ~/.zshrc && \
    echo 'ENABLE_CORRECTION="true"' >> ~/.zshrc && \
    echo 'plugins=(git)' >> ~/.zshrc && \
    echo 'source $ZSH/oh-my-zsh.sh' >> ~/.zshrc && \
    echo 'export LANG=en_US.UTF-8' >> ~/.zshrc && \
    echo '' >> ~/.zshrc && \
    echo '# Reload command to download and source .shrc from .files.git' >> ~/.zshrc && \
    echo 'reload() {' >> ~/.zshrc && \
    echo '  curl -fsSL https://raw.githubusercontent.com/yesitsfebreeze/.files/main/.shrc -o ~/.shrc' >> ~/.zshrc && \
    echo '  source ~/.shrc' >> ~/.zshrc && \
    echo '  update' >> ~/.zshrc && \
    echo '}' >> ~/.zshrc && \
    echo '' >> ~/.zshrc && \
    echo '# Sync command to download and rsync .files repo' >> ~/.zshrc && \
    echo 'sync() {' >> ~/.zshrc && \
    echo '  rm -rf /tmp/dotfiles' >> ~/.zshrc && \
    echo '  git clone https://github.com/yesitsfebreeze/.files.git /tmp/dotfiles' >> ~/.zshrc && \
    echo '  rsync -a /tmp/dotfiles/ .' >> ~/.zshrc && \
    echo '  rm -rf /tmp/dotfiles' >> ~/.zshrc && \
    echo '  source ~/.zshrc' >> ~/.zshrc && \
    echo '}' >> ~/.zshrc

WORKDIR /workspace
VOLUME /workspace

CMD ["zsh"]
