#!/usr/bin/env bash
# What the stack actually is, measured rather than read off the PRD. Read-only.
set -uo pipefail
cd "${1:-$HOME/dev/dotfiles}"
echo "--- source lines ---"
wc -l home/dot_local/bin/executable_cll \
      home/dot_local/bin/executable_litellm-env \
      home/dot_local/bin/executable_litellm-gen-config \
      home/dot_local/bin/executable_litellm-up \
      home/dot_local/bin/executable_llm-quota \
      home/dot_config/nushell/litellm.nu
echo "--- files naming litellm or cll (acceptance box 1 reads this) ---"
rg -l 'litellm|cll' home/ | sed 's/^/  /'
echo "  total: $(rg -l 'litellm|cll' home/ | wc -l | tr -d ' ')"
echo "--- chezmoi-managed targets of this stack ---"
chezmoi managed 2>/dev/null | grep -E 'litellm|/cll$|llm-quota'
echo "--- home/dot_config/litellm (PRD footprint claims it) ---"
[ -e home/dot_config/litellm ] && echo "  exists" || echo "  ABSENT in the source tree"
[ -f "$HOME/.config/litellm/config.yaml" ] \
  && echo "  ~/.config/litellm/config.yaml exists, generated by litellm-gen-config, unmanaged" \
  || echo "  no generated config on this machine"
echo "--- does cc/cr go through cll? (answer (c) assumes it does) ---"
rg -n 'cll' home/dot_config/nushell/claude.nu || echo "  no: _claude_run execs claude directly"
echo "--- live: catalogue and credit ---"
PATH="$HOME/.local/bin:$PATH" cll --catalog 2>/dev/null \
  | python3 -c "import json,sys; print('  catalogue rows:', len(json.load(sys.stdin)))" 2>/dev/null \
  || echo "  catalogue unavailable"
PATH="$HOME/.local/bin:$PATH" llm-quota --json 2>/dev/null \
  | python3 -c "import json,sys; [print(f'  {k}: {v.get(\"remaining\")} {v.get(\"unit\")}') for k,v in json.load(sys.stdin).items()]" 2>/dev/null \
  || echo "  quota unavailable"
