#!/usr/bin/env bash
# capsule's first-run credential setup (01-capsule/03, task C.3, spec02).
#
# chezmoi deploys this to ~/.config/capsule/setup-credentials.sh (0755, the
# `executable_` prefix). The capsule CLI mounts it read-only at
# /opt/capsule/setup-credentials.sh and runs it ONCE, as `dev`, on the create
# path. It turns the read-only host mounts into working SSH, git and agent
# auth inside the container. Nothing it writes ever leaves the container.
#
# IT LIVES BESIDE THE DOCKERFILE, AND THAT DIRECTORY IS THE BUILD CONTEXT.
# A script here is fine — the Dockerfile has no COPY and no ADD, and C.1's
# gate keeps it that way — but a credential here would be one `COPY .` from
# an image layer. Never write generated material into ~/.config/capsule.
#
# WHAT IT MAY ASSUME
#   * It runs as `dev` (the image's unprivileged user, C.1 R5). It needs no
#     root, creates no user and escalates no privilege: the image already
#     made the user, which is the single biggest simplification over the
#     legacy setup script, which created users, edited the privileged-user
#     policy file, and cloned a dotfiles repo over SSH before any credential
#     was known to work. The gate greps this file for both spellings, so
#     they are kept out of it entirely and a hit is proof of a regression.
#   * The image has git, openssh-client, bash, zsh and coreutils (C.1 R2 and
#     its support set). It installs NOTHING — the toolbox is closed (C.1 R7).
#   * Mounts, all read-only, all optional: /opt/capsule/host/ssh,
#     /opt/capsule/host/gitconfig, and /opt/capsule/creds holding
#     git-credentials, claude-credentials.json, claude.json and
#     opencode-auth.json.
#
# WHAT IT MUST NEVER DO
#   * Write, chmod or chown anything under /opt/capsule — those are the
#     read-only host mounts.
#   * Write outside $HOME.
#   * Print a credential, not even truncated: this runs with its output on
#     the user's terminal, and a token in the scrollback is a token in the
#     scrollback.
#   * Install a package, or create a user.
#
# It is IDEMPOTENT: `capsule --rebuild` re-runs it, and so may a human
# debugging inside a capsule. Every optional source is guarded — a missing
# source is one warning on stderr and a continue, never an abort.

set -eu

SSH_SRC=/opt/capsule/host/ssh
GITCONFIG_SRC=/opt/capsule/host/gitconfig
CREDS=/opt/capsule/creds

warn() { printf 'capsule-setup: %s\n' "$*" >&2; }

# ── 1 — SSH (R1) ────────────────────────────────────────────────────────────
#
# The keys are COPIED rather than used from the mount, and that is R1's point
# with its reason: Docker Desktop's macOS file sharing does not carry host
# file modes into the container in a form ssh will accept, and ssh refuses a
# private key it considers group- or world-readable ("Permissions ... are too
# open"). The mount stays read-only; the usable copy is container-local, so
# fixing modes can never change the host's keys.
install -d -m 700 "$HOME/.ssh"

if [ -d "$SSH_SRC" ]; then
  privkeys=""
  for f in "$SSH_SRC"/id_*; do
    [ -f "$f" ] || continue
    b="$(basename "$f")"
    case "$b" in
      *.pub) install -m 644 "$f" "$HOME/.ssh/$b" ;;
      *)     install -m 600 "$f" "$HOME/.ssh/$b"
             privkeys="$privkeys $b" ;;
    esac
  done

  # NOTHING ELSE IS COPIED — explicitly not the host's own ~/.ssh/config and
  # not .DS_Store. The host config is macOS-shaped: on this machine it is
  # `Include ~/.orbstack/ssh/config`, a path that does not exist here, and
  # the common macOS `UseKeychain yes` line makes Linux ssh abort EVERY
  # invocation with "Bad configuration option: usekeychain". The legacy
  # script copied the whole directory and inherited exactly that risk.

  # known_hosts: seeded from the host copy only when we do not have one yet,
  # so a second run never re-overwrites lines this script appended.
  if [ ! -f "$HOME/.ssh/known_hosts" ] && [ -f "$SSH_SRC/known_hosts" ]; then
    install -m 600 "$SSH_SRC/known_hosts" "$HOME/.ssh/known_hosts"
  fi

  if [ -n "$privkeys" ]; then
    # $privkeys is a space-separated accumulator, and the split into words
    # is exactly what is wanted here.
    # shellcheck disable=SC2086
    sorted="$(printf '%s\n' $privkeys | LC_ALL=C sort)"
    nkeys="$(printf '%s\n' "$sorted" | wc -l | tr -d ' ')"
    # ONE IdentityFile PER COPIED KEY, not a guessed "preferred" name: this
    # host has both id_gh and id_rsa, and ssh tries each. `IdentitiesOnly
    # yes` stops ssh offering anything else. Keep the count small — past
    # about five keys GitHub answers "Too many authentication failures"
    # before ssh reaches the right one.
    if [ "$nkeys" -gt 5 ]; then
      warn "$nkeys private keys copied; GitHub may answer \"Too many authentication failures\" before the right one is tried"
    fi
    # The ssh config is GENERATED, never inherited.
    {
      printf '# generated by capsule first-run credential setup\n'
      printf 'Host github.com\n'
      # One word per key, deliberately split.
      # shellcheck disable=SC2086
      for k in $sorted; do printf '  IdentityFile ~/.ssh/%s\n' "$k"; done
      printf '  IdentitiesOnly yes\n'
      printf '  UserKnownHostsFile ~/.ssh/known_hosts\n'
      # accept-new, and NEVER the `no` value: `no` disables host
      # verification entirely instead of only the prompt. accept-new is the
      # backstop that keeps the first connection from prompting when the
      # keyscan below could not run. The gate greps this file for the
      # forbidden spelling, so it is kept out of this comment entirely and a
      # hit is proof of a regression.
      printf '  StrictHostKeyChecking accept-new\n'
    } > "$HOME/.ssh/config"
    chmod 600 "$HOME/.ssh/config"

    # Pre-add GitHub's host keys (R1). Best-effort: it needs the network, so
    # a failure is a warning, not an abort — accept-new covers it.
    if [ ! -f "$HOME/.ssh/known_hosts" ] || ! grep -q 'github\.com' "$HOME/.ssh/known_hosts"; then
      ks="$(mktemp)"
      if ssh-keyscan -T 5 -t rsa,ecdsa,ed25519 github.com > "$ks" 2>/dev/null && [ -s "$ks" ]; then
        cat "$ks" >> "$HOME/.ssh/known_hosts"
        chmod 600 "$HOME/.ssh/known_hosts"
      else
        warn "ssh-keyscan github.com failed; StrictHostKeyChecking accept-new is the backstop"
      fi
      rm -f "$ks"
    fi
  else
    warn "$SSH_SRC holds no id_* private key; no ssh config written"
  fi
else
  warn "$SSH_SRC is not mounted; SSH will not work in this capsule"
fi

# ── 2 — git identity and HTTPS credentials (R2, R3) ─────────────────────────
#
# Container-local and WRITABLE (0600), so `git config --global` inside a
# capsule still works. Every line after the include is a correction to
# something the host config does that cannot work in a container, and each
# one costs a debugging session if it is dropped:
#
#   * The host routes github.com through `helper = !gh auth git-credential`.
#     `gh` is NOT in the image's closed toolbox, so an inherited helper makes
#     every HTTPS push shell out to a missing binary. The empty `helper =`
#     reset followed by the store helper is the same trick the host config
#     itself uses — and it must be repeated PER URL, because a URL-scoped
#     helper list overrides the generic one: a top-level reset alone leaves
#     `!gh auth git-credential` in place for github.com, which is the whole
#     point of the exercise.
#   * `core.pager = delta` and `interactive.diffFilter = delta --color-only`
#     are inherited from the host, and delta is not in the image either —
#     without these overrides `git diff` and `git log` fail inside every
#     capsule. `cat` is a no-op filter; leaving diffFilter empty makes git
#     run an empty command.
#   * The include is what satisfies R2: author, committer, aliases and every
#     other host preference arrive from the mounted file, so authorship
#     inside a capsule matches the host without copying anything.
#   * The host's `[includeIf "gitdir:~/dev/_pi_extensions/"]` names a path
#     that does not exist here. Git ignores a missing include silently, so
#     nothing is owed — noted so nobody "fixes" it.
#
# The credential store file is read STRAIGHT FROM THE READ-ONLY MOUNT.
# Nothing is copied, and that is what makes a rotated token heal: the host
# rewrites that file and a running container sees the new content
# immediately. `git credential-store` only writes on `approve`, which git
# does not call for a credential a helper supplied, so a read-only store is
# the normal path and not a lurking error.
if [ ! -f "$GITCONFIG_SRC" ]; then
  warn "$GITCONFIG_SRC is not mounted; git identity and aliases will not match the host"
fi
if [ ! -f "$CREDS/git-credentials" ]; then
  warn "$CREDS/git-credentials is absent; HTTPS pushes will have no credential"
fi
{
  printf '# generated by capsule first-run credential setup — container-local\n'
  printf '[include]\n\tpath = %s\n' "$GITCONFIG_SRC"
  printf '[credential]\n\thelper =\n\thelper = store --file=%s/git-credentials\n' "$CREDS"
  printf '[credential "https://github.com"]\n\thelper =\n\thelper = store --file=%s/git-credentials\n' "$CREDS"
  printf '[credential "https://gist.github.com"]\n\thelper =\n\thelper = store --file=%s/git-credentials\n' "$CREDS"
  printf '[core]\n\tpager = less -FRX\n'
  printf '[interactive]\n\tdiffFilter = cat\n'
} > "$HOME/.gitconfig"
chmod 600 "$HOME/.gitconfig"

# ── 3 — the agents (R4) ─────────────────────────────────────────────────────
#
# A SYMLINK for the credential and a COPY for .claude.json, and the asymmetry
# is the interesting part:
#
#   * The credential is symlinked into the read-only mount so a host-side
#     refresh reaches even a RUNNING capsule, and so the container
#     physically cannot write a token anywhere. It also cannot run its own
#     OAuth refresh — which is deliberate, not an oversight: Claude's
#     refresh ROTATES the refresh token, so a capsule refreshing on its own
#     would invalidate the host's login. Borrowing the host credential and
#     failing closed is the correct trade. The visible failure mode is on
#     the manual checklist: if the access token expires while a long-lived
#     capsule sits idle, `claude` inside it asks to log in, and re-mounting
#     (or running `claude` on the host) heals it.
#   * .claude.json is written by Claude Code on every run, so it must be
#     writable and container-local; a symlink into the read-only mount would
#     make the agent fail on startup. It is the filtered six-key projection
#     the host exports, so the copy carries onboarding state and account
#     identity and no token.
if [ -f "$CREDS/claude-credentials.json" ]; then
  install -d -m 700 "$HOME/.claude"
  ln -sfn "$CREDS/claude-credentials.json" "$HOME/.claude/.credentials.json"
else
  warn "$CREDS/claude-credentials.json is absent; claude will ask to log in"
fi

if [ -f "$CREDS/claude.json" ]; then
  install -m 600 "$CREDS/claude.json" "$HOME/.claude.json"
else
  warn "$CREDS/claude.json is absent; claude may show its onboarding prompts"
fi

# Same reasoning for OpenCode. Everything else it writes — its database,
# logs, snapshots — stays container-local, which is the point: the host's
# 94 MB SQLite store is deliberately not shared into a container.
if [ -f "$CREDS/opencode-auth.json" ]; then
  install -d -m 700 "$HOME/.local/share/opencode"
  ln -sfn "$CREDS/opencode-auth.json" "$HOME/.local/share/opencode/auth.json"
else
  warn "$CREDS/opencode-auth.json is absent; opencode will ask to log in"
fi

printf 'capsule-setup: done\n'
