#!/usr/bin/env bash

# executable_setup-credentials.sh
# Why this file is shaped the way it is:
#   manual → internals/capsule


set -eu

SSH_SRC=/opt/capsule/host/ssh
GITCONFIG_SRC=/opt/capsule/host/gitconfig
CREDS=/opt/capsule/creds

warn() { printf 'capsule-setup: %s\n' "$*" >&2; }

# ── 1 — SSH (R1) ────────────────────────────────────────────────────────────
install -d -m 700 "$HOME/.ssh"

if [ -d "$SSH_SRC" ]; then
  privkeys=""
  for f in "$SSH_SRC"/id_*; do
    [ -f "$f" ] || continue
    b="$(basename "$f")"
    case "$b" in
      *.pub) install -m 644 "$f" "$HOME/.ssh/$b" ;;
      *)     install -m 600 "$f" "$HOME/.ssh/$b"
             privkeys="$privkeys $b" ;;
    esac
  done

  if [ ! -f "$HOME/.ssh/known_hosts" ] && [ -f "$SSH_SRC/known_hosts" ]; then
    install -m 600 "$SSH_SRC/known_hosts" "$HOME/.ssh/known_hosts"
  fi

  if [ -n "$privkeys" ]; then
    sorted="$(printf '%s\n' $privkeys | LC_ALL=C sort)"
    nkeys="$(printf '%s\n' "$sorted" | wc -l | tr -d ' ')"
    if [ "$nkeys" -gt 5 ]; then
      warn "$nkeys private keys copied; GitHub may answer \"Too many authentication failures\" before the right one is tried"
    fi
    {
      printf '# generated by capsule first-run credential setup\n'
      printf 'Host github.com\n'
      for k in $sorted; do printf '  IdentityFile ~/.ssh/%s\n' "$k"; done
      printf '  IdentitiesOnly yes\n'
      printf '  UserKnownHostsFile ~/.ssh/known_hosts\n'
      printf '  StrictHostKeyChecking accept-new\n'
    } > "$HOME/.ssh/config"
    chmod 600 "$HOME/.ssh/config"

    if [ ! -f "$HOME/.ssh/known_hosts" ] || ! grep -q 'github\.com' "$HOME/.ssh/known_hosts"; then
      ks="$(mktemp)"
      if ssh-keyscan -T 5 -t rsa,ecdsa,ed25519 github.com > "$ks" 2>/dev/null && [ -s "$ks" ]; then
        cat "$ks" >> "$HOME/.ssh/known_hosts"
        chmod 600 "$HOME/.ssh/known_hosts"
      else
        warn "ssh-keyscan github.com failed; StrictHostKeyChecking accept-new is the backstop"
      fi
      rm -f "$ks"
    fi
  else
    warn "$SSH_SRC holds no id_* private key; no ssh config written"
  fi
else
  warn "$SSH_SRC is not mounted; SSH will not work in this capsule"
fi

# ── 2 — git identity and HTTPS credentials (R2, R3) ─────────────────────────
if [ ! -f "$GITCONFIG_SRC" ]; then
  warn "$GITCONFIG_SRC is not mounted; git identity and aliases will not match the host"
fi
if [ ! -f "$CREDS/git-credentials" ]; then
  warn "$CREDS/git-credentials is absent; HTTPS pushes will have no credential"
fi
{
  printf '# generated by capsule first-run credential setup — container-local\n'
  printf '[include]\n\tpath = %s\n' "$GITCONFIG_SRC"
  printf '[credential]\n\thelper =\n\thelper = store --file=%s/git-credentials\n' "$CREDS"
  printf '[credential "https://github.com"]\n\thelper =\n\thelper = store --file=%s/git-credentials\n' "$CREDS"
  printf '[credential "https://gist.github.com"]\n\thelper =\n\thelper = store --file=%s/git-credentials\n' "$CREDS"
  printf '[core]\n\tpager = less -FRX\n'
  printf '[interactive]\n\tdiffFilter = cat\n'
} > "$HOME/.gitconfig"
chmod 600 "$HOME/.gitconfig"

# ── 3 — the agents (R4) ─────────────────────────────────────────────────────
if [ -f "$CREDS/claude-credentials.json" ]; then
  install -d -m 700 "$HOME/.claude"
  ln -sfn "$CREDS/claude-credentials.json" "$HOME/.claude/.credentials.json"
else
  warn "$CREDS/claude-credentials.json is absent; claude will ask to log in"
fi

if [ -f "$CREDS/claude.json" ]; then
  install -m 600 "$CREDS/claude.json" "$HOME/.claude.json"
else
  warn "$CREDS/claude.json is absent; claude may show its onboarding prompts"
fi

if [ -f "$CREDS/opencode-auth.json" ]; then
  install -d -m 700 "$HOME/.local/share/opencode"
  ln -sfn "$CREDS/opencode-auth.json" "$HOME/.local/share/opencode/auth.json"
else
  warn "$CREDS/opencode-auth.json is absent; opencode will ask to log in"
fi

printf 'capsule-setup: done\n'
