#!/usr/bin/env python3
"""The memos gate. One command, two halves:

  check       every memo in the index, every link resolving, every folder its
              kind, every kind declared, one claim per memo — one problem per
              line, exit 1 on any
  (default)   regenerate the indexes first, then check — what `just memos-check` runs

A memo that is not in the index is not in the record, and an index written by
hand drifts from the memos it names, so no index is authored by hand:
`generate` rewrites every level from the memos themselves. Structure only —
a claim's truth is the routines' job, not the gate's.
"""
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MEMOS = REPO / "memos"
BUNDLES = REPO / "memos-bundles.txt"
NOT_A_HOME = {"dashboards"}
TEMPLATE_HEADINGS = {
    "## Decision", "## Why", "## Consequences", "## Do", "## Check",
    "## How you work", "## Voice", "## Built from",
}
GENERATED = "_index_"
WIKILINK = re.compile(r"(?<!`)\[\[([^\]|#]+?)(?:[|#][^\]]*)?\]\](?!`)")


def is_generated(p: Path) -> bool:
    return p.stem == GENERATED


def md_in(directory: Path, out: list) -> None:
    if not directory.is_dir():
        return
    for p in sorted(directory.iterdir()):
        if p.is_file() and p.suffix == ".md" and not is_generated(p):
            out.append(p)


def homes(memos: Path) -> list:
    if not memos.is_dir():
        return []
    return sorted(d for d in memos.iterdir()
                  if d.is_dir() and not d.name.startswith(".")
                  and d.name not in NOT_A_HOME)


def indexed_memos(memos: Path) -> list:
    out: list = []
    for h in homes(memos):
        md_in(h, out)
    return out


def home_of(memos: Path, f: Path) -> str:
    try:
        return f.parent.relative_to(memos).as_posix()
    except ValueError:
        return ""


def frontmatter(text: str, key: str) -> str:
    prefix = key + ":"
    for line in text.splitlines():
        line = line.rstrip()
        if line.startswith(prefix):
            return line[len(prefix):].strip()
    return ""


def body(text: str) -> str:
    if text.startswith("---\n"):
        _, _, rest = text.partition("\n---")
        if rest:
            return rest
    return text


def wikilinks(text: str) -> list:
    # A doubled bracket inside a code span or a fence is the record quoting
    # the syntax, not citing a memo — the gate reads what a fold would fold.
    text = re.sub(r"```.*?```", "", text, flags=re.S)
    text = re.sub(r"`[^`\n]*`", "", text)
    return WIKILINK.findall(text)


def rows(memos: Path) -> list:
    out = []
    for f in indexed_memos(memos):
        text = f.read_text()
        out.append({
            "leaf": f.stem,
            "home": home_of(memos, f),
            "kind": frontmatter(text, "kind"),
            "description": frontmatter(text, "description"),
            "read_when": frontmatter(text, "read_when"),
            "links": wikilinks(body(text)),
        })
    return out


def unquote(s: str) -> str:
    t = s.strip()
    if t.startswith('"') and t.endswith('"') and len(t) >= 2:
        return t[1:-1]
    return t


def generate(memos: Path, all_rows: list) -> None:
    declarations = {}
    for r in all_rows:
        if r["home"] == "system" and r["kind"] == "type":
            text = (memos / "system" / f"{r['leaf']}.md").read_text()
            t = frontmatter(text, "type")
            if not t:
                continue
            declarations[t] = r
    paths = {r["leaf"]: f"{r['home']}/{r['leaf']}.md" for r in all_rows}
    kinds = {}
    for kind, declaration in declarations.items():
        folder = "system" if kind == "type" else kind
        selected = [r for r in all_rows if r["kind"] == kind]
        entries = {}
        for r in selected:
            entries[r["leaf"]] = {
                "path": paths[r["leaf"]],
                "description": unquote(r["description"]),
                "read_when": unquote(r["read_when"]),
                "links": {l: paths.get(l) for l in r["links"]},
            }
        d = memos / folder
        d.mkdir(parents=True, exist_ok=True)
        (d / "index.json").write_text(json.dumps(
            {"kind": kind, "memo_count": len(selected), "memos": entries}, indent=2) + "\n")
        kinds[kind] = {
            "description": unquote(declaration["description"]),
            "read_when": unquote(declaration["read_when"]),
            "memo_count": len(selected),
            "declaration": paths[declaration["leaf"]],
            "index": f"{folder}/index.json",
        }
    seen_homes = {("system" if k == "type" else k) for k in declarations}
    seen_homes.update(r["home"] for r in all_rows)
    for h in sorted(seen_homes):
        md = ("<!-- generated by scripts/memos-check.py; edit the memos, not this file -->\n\n"
              f"# {h}\n\n| memo | is | read when |\n|---|---|---|\n")
        for r in all_rows:
            if r["home"] == h or (h != "system" and r["kind"] == h):
                md += f"| [[{r['leaf']}]] | {unquote(r['description'])} | {unquote(r['read_when'])} |\n"
        d = memos / h
        d.mkdir(parents=True, exist_ok=True)
        (d / f"{GENERATED}.md").write_text(md)
    (memos / "index.json").write_text(json.dumps(
        {"kinds": kinds, "memo_count": len(all_rows)}, indent=2) + "\n")


def check(memos: Path, bundles_file: Path) -> list:
    if not (memos / "SYSTEM.md").is_file():
        return [f"{memos / 'SYSTEM.md'} is missing — the record is not here"]
    bundles = []
    if bundles_file.is_file():
        bundles = [l.strip() for l in bundles_file.read_text().splitlines()
                   if l.strip() and not l.startswith("#")]
    fails = []
    listed = indexed_memos(memos)

    # Leaf names are unique across memos/ — a link cannot tell the folders apart.
    counts: dict = {}
    for h in homes(memos):
        for p in h.rglob("*.md"):
            if is_generated(p):
                continue
            counts[p.stem] = counts.get(p.stem, 0) + 1
    for name, count in sorted(counts.items()):
        if count > 1:
            fails.append(f"duplicate leaf: [[{name}]] names {count} files")

    # A kind is what a `kind: type` memo in system/ declares with its `type:`.
    declared = []
    for f in listed:
        if home_of(memos, f) != "system":
            continue
        text = f.read_text()
        if frontmatter(text, "kind") != "type":
            continue
        t = frontmatter(text, "type")
        if not t:
            fails.append(f"no type: memos/{home_of(memos, f)}/{f.name} declares nothing")
            continue
        declared.append(t)
    declared.sort()

    for f in listed:
        text = f.read_text()
        h = home_of(memos, f)
        rel = f"memos/{h}/{f.name}"
        kind = frontmatter(text, "kind")
        if not kind:
            fails.append(f"no kind: {rel}")
            continue
        if kind not in declared:
            fails.append(f"undeclared kind `{kind}`: {rel} — write system/{kind}.md "
                         f"with `kind: type` and `type: {kind}`")
        if h != "system" and h != kind:
            fails.append(f"wrong folder: {rel} carries `kind: {kind}` and lives in {h}/")
        if kind in ("documentation", "routine", "persona"):
            continue
        extra = sum(1 for l in text.splitlines()
                    if l.rstrip().startswith("## ") and l.rstrip() not in TEMPLATE_HEADINGS)
        name = f.stem
        if extra and name not in bundles:
            fails.append(f"not atomic: {rel} holds {extra} free-form sections — "
                         "split it, one claim per memo")
        if not extra and name in bundles:
            fails.append(f"stale bundle entry: {name} is atomic now — "
                         "drop its line from memos-bundles.txt")

    # A link naming no file folds to an edge to nothing. SYSTEM.md carries no
    # frontmatter, so its name is the one leaf the gate knows without a file.
    known = {p.stem for h in homes(memos) for p in h.rglob("*.md")}
    known.add("SYSTEM")
    for f in listed + [memos / "SYSTEM.md"]:
        text = f.read_text()
        rel = f"memos/{home_of(memos, f)}/{f.name}" if f != memos / "SYSTEM.md" else "memos/SYSTEM.md"
        for name in wikilinks(body(text)):
            if name not in known:
                fails.append(f"link to nothing: [[{name}]] in {rel}")
    return fails


def main() -> int:
    args = sys.argv[1:]
    if args[:1] == ["generate"]:
        r = rows(MEMOS)
        generate(MEMOS, r)
        print(f"memos index: {len(r)} memos")
        return 0
    all_rows = rows(MEMOS)
    generate(MEMOS, all_rows)
    fails = check(MEMOS, BUNDLES)
    if fails:
        print(f"{len(fails)} memos gate failure(s):", file=sys.stderr)
        for f in fails:
            print(f"  {f}", file=sys.stderr)
        return 1
    print(f"memos index: {len(all_rows)} memos")
    return 0


if __name__ == "__main__":
    sys.exit(main())