// Generates the manual pages from the four .nuon surface files that `help`
// itself reads, so the site and the shell manual cannot drift apart.
// Run: npm run generate
import { execFileSync } from 'node:child_process'
import { mkdirSync, writeFileSync, rmSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const HELP = resolve(root, '../home/dot_config/nushell/help')
const OUT = join(root, 'content/docs/manual')
const SURFACES = ['shell', 'nvim', 'terminal', 'capsule']

const nuon = (f) =>
  JSON.parse(
    execFileSync('nu', ['-c', `open "${join(HELP, f)}" | to json`], {
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
    }),
  )

// MDX reads `<` as JSX and `{` as an expression. Escape them, but only
// outside code spans — inside backticks MDX interprets nothing, and the
// entries lean on that for `<leader>`, `<S-h>` and friends.
const escapeOutsideCode = (s) =>
  String(s ?? '')
    .split(/(`+[^`]*`+)/g)
    .map((part, i) =>
      i % 2 === 1 ? part : part.replace(/</g, '&lt;').replace(/\{/g, '&#123;'),
    )
    .join('')

const slug = (s) =>
  String(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')

const invocation = (e) => e.cmd ?? e.key ?? e.title

const MODE_LABEL = {
  shell: 'Shell',
  terminal: 'Terminal',
  container: 'Container',
}
const modeLabel = (m) => {
  if (!m) return null
  if (MODE_LABEL[m]) return MODE_LABEL[m]
  if (m.startsWith('nvim:')) return `Neovim — ${m.slice(5)} mode`
  return m
}

const topics = nuon('topics.nuon')
const entries = SURFACES.flatMap((s) =>
  nuon(`${s}.nuon`).map((e) => ({ ...e, surface: s })),
)

// invocation -> where its entry lives, so `also` becomes a real link
const index = new Map()
for (const e of entries) {
  const t = topics.find((t) => t.id === e.topic)
  if (!t) continue
  index.set(invocation(e), `/docs/manual/${t.id}#${slug(invocation(e))}`)
}

rmSync(OUT, { recursive: true, force: true })
mkdirSync(OUT, { recursive: true })

const pages = []
for (const topic of topics) {
  const mine = entries.filter((e) => e.topic === topic.id)
  if (mine.length === 0) continue

  const body = mine
    .map((e) => {
      const inv = invocation(e)
      const out = [`## \`${inv}\``, '', `**${escapeOutsideCode(e.title)}**`, '']

      const label = modeLabel(e.mode)
      if (label) out.push(`*${label}*`, '')

      if (e.use) out.push(escapeOutsideCode(e.use), '')
      if (e.why)
        out.push(
          '<Callout title="Why it is this way">',
          escapeOutsideCode(e.why),
          '</Callout>',
          '',
        )

      const also = (e.also ?? [])
        .map((a) => (index.has(a) ? `[\`${a}\`](${index.get(a)})` : `\`${a}\``))
        .join(' · ')
      const meta = []
      if (also) meta.push(`See also: ${also}`)
      if (e.source) meta.push(`Spec: \`${e.source}\``)
      if (meta.length) out.push(meta.join('  \n'), '')

      return out.join('\n')
    })
    .join('\n')

  const page = [
    '---',
    `title: ${JSON.stringify(topic.title)}`,
    `description: ${JSON.stringify(topic.summary)}`,
    '---',
    '',
    '{/* GENERATED by scripts/generate-manual.mjs — edit the .nuon surface, not this file. */}',
    '',
    body,
  ].join('\n')

  writeFileSync(join(OUT, `${topic.id}.mdx`), page)
  pages.push({ id: topic.id, count: mine.length })
}

writeFileSync(
  join(OUT, 'meta.json'),
  JSON.stringify(
    { title: 'Manual', description: 'Every key, command and alias', pages: pages.map((p) => p.id) },
    null,
    2,
  ) + '\n',
)

const total = pages.reduce((n, p) => n + p.count, 0)
console.log(`manual: ${total} entries across ${pages.length} topics`)
for (const p of pages) console.log(`  ${p.id.padEnd(12)} ${p.count}`)
